source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'iosBleSdkTestApp' do
    #pod 'PolarBleSdk', '~> 3.2'
    pod 'PolarBleSdk', :git => 'https://github.com/polarofficial/polar-ble-sdk.git', :branch => 'time-stamps-calculated-by-the-sdk'
end
