// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pftp_response.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "google/GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PbDate;
@class PbPFtpEntry;
@class PbSystemDateTime;
@class PbTime;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PftpResponseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PftpResponseRoot : GPBRootObject
@end

#pragma mark - PbPFtpEntry

typedef GPB_ENUM(PbPFtpEntry_FieldNumber) {
  PbPFtpEntry_FieldNumber_Name = 1,
  PbPFtpEntry_FieldNumber_Size = 2,
  PbPFtpEntry_FieldNumber_Created = 3,
  PbPFtpEntry_FieldNumber_Modified = 4,
  PbPFtpEntry_FieldNumber_Touched = 5,
};

/**
 *
 * Class for presenting filesystem entry, i.e. file or directory.
 * - The entry is directory if the name ends to directory delimiter, i.e. '/' character. F.ex. "directory/" or "directory.ext/".
 * - Otherwise the entry is considered to be a file. F.ex. "file" or "file.ext".
 * - See PbPFtpDirectory below for response to a directory listing operation.
 **/
@interface PbPFtpEntry : GPBMessage

/** Name of the file or directory. Ending directory delimiter designates directory entry. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

/** Size of the file in bytes, or 0 for directory entry. */
@property(nonatomic, readwrite) uint64_t size;

@property(nonatomic, readwrite) BOOL hasSize;
/** If present, entry's creation date/time. I.e. instant of the first write. */
@property(nonatomic, readwrite, strong, null_resettable) PbSystemDateTime *created;
/** Test to see if @c created has been set. */
@property(nonatomic, readwrite) BOOL hasCreated;

/** If present, entry's last modified date/time.  I.e. instant of the last write. */
@property(nonatomic, readwrite, strong, null_resettable) PbSystemDateTime *modified;
/** Test to see if @c modified has been set. */
@property(nonatomic, readwrite) BOOL hasModified;

/** If present, entry's last touched date/time. I.e. instant of the last read or write. */
@property(nonatomic, readwrite, strong, null_resettable) PbSystemDateTime *touched;
/** Test to see if @c touched has been set. */
@property(nonatomic, readwrite) BOOL hasTouched;

@end

#pragma mark - PbPFtpDirectory

typedef GPB_ENUM(PbPFtpDirectory_FieldNumber) {
  PbPFtpDirectory_FieldNumber_EntriesArray = 1,
};

/**
 *
 * Response to GET directory list operation.
 * The PbPFtpDirectory message is to be transmitted in the response data (SAGRFC56).
 **/
@interface PbPFtpDirectory : GPBMessage

/** List of unique entries in a directory. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PbPFtpEntry*> *entriesArray;
/** The number of items in @c entriesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger entriesArray_Count;

@end

#pragma mark - PbPFtpIdentifyDeviceResult

typedef GPB_ENUM(PbPFtpIdentifyDeviceResult_FieldNumber) {
  PbPFtpIdentifyDeviceResult_FieldNumber_DeviceId = 1,
};

/**
 *
 * Response data to IDENTIFY_DEVICE query in pftp_request.proto.
 **/
@interface PbPFtpIdentifyDeviceResult : GPBMessage

/** Device's id (SAGRFC19). */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

@end

#pragma mark - PbPFtpGetSystemTimeResult

typedef GPB_ENUM(PbPFtpGetSystemTimeResult_FieldNumber) {
  PbPFtpGetSystemTimeResult_FieldNumber_Date = 1,
  PbPFtpGetSystemTimeResult_FieldNumber_Time = 2,
  PbPFtpGetSystemTimeResult_FieldNumber_Trusted = 3,
};

/**
 *
 * Response data to GET_SYSTEM_TIME query in pftp_request.proto.
 **/
@interface PbPFtpGetSystemTimeResult : GPBMessage

/** UTC date. */
@property(nonatomic, readwrite, strong, null_resettable) PbDate *date;
/** Test to see if @c date has been set. */
@property(nonatomic, readwrite) BOOL hasDate;

/** UTC time. */
@property(nonatomic, readwrite, strong, null_resettable) PbTime *time;
/** Test to see if @c time has been set. */
@property(nonatomic, readwrite) BOOL hasTime;

/** True, if the date and time can be trusted. */
@property(nonatomic, readwrite) BOOL trusted;

@property(nonatomic, readwrite) BOOL hasTrusted;
@end

#pragma mark - PbPFtpGetLocalTimeResult

typedef GPB_ENUM(PbPFtpGetLocalTimeResult_FieldNumber) {
  PbPFtpGetLocalTimeResult_FieldNumber_Date = 1,
  PbPFtpGetLocalTimeResult_FieldNumber_Time = 2,
  PbPFtpGetLocalTimeResult_FieldNumber_TzOffset = 3,
};

/**
 *
 * Response data to GET_LOCAL_TIME query in pftp_request.proto.
 **/
@interface PbPFtpGetLocalTimeResult : GPBMessage

/** Local date. */
@property(nonatomic, readwrite, strong, null_resettable) PbDate *date;
/** Test to see if @c date has been set. */
@property(nonatomic, readwrite) BOOL hasDate;

/** Local time. */
@property(nonatomic, readwrite, strong, null_resettable) PbTime *time;
/** Test to see if @c time has been set. */
@property(nonatomic, readwrite) BOOL hasTime;

/** If present, timezone offset in 1 minute precision (-12h = -720min to +12h = +720min). */
@property(nonatomic, readwrite) int32_t tzOffset;

@property(nonatomic, readwrite) BOOL hasTzOffset;
@end

#pragma mark - PbPFtpDiskSpaceResult

typedef GPB_ENUM(PbPFtpDiskSpaceResult_FieldNumber) {
  PbPFtpDiskSpaceResult_FieldNumber_FragmentSize = 1,
  PbPFtpDiskSpaceResult_FieldNumber_TotalFragments = 2,
  PbPFtpDiskSpaceResult_FieldNumber_FreeFragments = 3,
};

/**
 *
 * Response data to GET_DISK_SPACE and CLEANUP_DISK_SPACE queries in pftp_request.proto.
 **/
@interface PbPFtpDiskSpaceResult : GPBMessage

/** Filesystem fragment size. Smallest allocatable filesystem unit. */
@property(nonatomic, readwrite) uint32_t fragmentSize;

@property(nonatomic, readwrite) BOOL hasFragmentSize;
/** Total size of the filesystem in fragments. */
@property(nonatomic, readwrite) uint64_t totalFragments;

@property(nonatomic, readwrite) BOOL hasTotalFragments;
/** Amount of available fragments. */
@property(nonatomic, readwrite) uint64_t freeFragments;

@property(nonatomic, readwrite) BOOL hasFreeFragments;
@end

#pragma mark - PbPFtpGenerateChallengeTokenResult

typedef GPB_ENUM(PbPFtpGenerateChallengeTokenResult_FieldNumber) {
  PbPFtpGenerateChallengeTokenResult_FieldNumber_Token = 1,
};

/**
 *
 * Response data to GENERATE_CHALLENGE_TOKEN query in pftp_request.proto.
 **/
@interface PbPFtpGenerateChallengeTokenResult : GPBMessage

/** Generated challenge token. Exactly 16 bytes. */
@property(nonatomic, readwrite, copy, null_resettable) NSData *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

@end

#pragma mark - PbPFtpBatteryStatusResult

typedef GPB_ENUM(PbPFtpBatteryStatusResult_FieldNumber) {
  PbPFtpBatteryStatusResult_FieldNumber_BatteryStatus = 1,
  PbPFtpBatteryStatusResult_FieldNumber_Charging = 2,
};

/**
 *
 * Response data to GET_BATTERY_STATUS query in pftp_request.proto and used as
 * parameters in BATTERY_STATUS notification defined in pftp_notification.proto.
 **/
@interface PbPFtpBatteryStatusResult : GPBMessage

/**
 * Battery status in percentage
 * Range [0-100%]
 **/
@property(nonatomic, readwrite) uint32_t batteryStatus;

@property(nonatomic, readwrite) BOOL hasBatteryStatus;
@property(nonatomic, readwrite) BOOL charging;

@property(nonatomic, readwrite) BOOL hasCharging;
@end

#pragma mark - PbPFtpGetInactivityPreAlertResult

typedef GPB_ENUM(PbPFtpGetInactivityPreAlertResult_FieldNumber) {
  PbPFtpGetInactivityPreAlertResult_FieldNumber_InactivityPreAlertOn = 1,
};

/**
 *
 * Response data to GET_INACTIVITY_PRE_ALERT query in pftp_request.proto.
 **/
@interface PbPFtpGetInactivityPreAlertResult : GPBMessage

/** True, if inactivity pre-alert has triggered. False after pre-alert's time window has expired. */
@property(nonatomic, readwrite) BOOL inactivityPreAlertOn;

@property(nonatomic, readwrite) BOOL hasInactivityPreAlertOn;
@end

#pragma mark - PbRequestRecordingStatusResult

typedef GPB_ENUM(PbRequestRecordingStatusResult_FieldNumber) {
  PbRequestRecordingStatusResult_FieldNumber_RecordingOn = 1,
  PbRequestRecordingStatusResult_FieldNumber_SampleDataIdentifier = 2,
};

/**
 *
 * Response data to REQUEST_RECORDING_STATUS query in pftp_request.proto.
 **/
@interface PbRequestRecordingStatusResult : GPBMessage

@property(nonatomic, readwrite) BOOL recordingOn;

@property(nonatomic, readwrite) BOOL hasRecordingOn;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sampleDataIdentifier;
/** Test to see if @c sampleDataIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasSampleDataIdentifier;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
