source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'
use_frameworks!

def swift_protobuf_pod
  pod 'SwiftProtobuf', '~> 1.0'
end

def zip_pod
  pod 'Zip', '~> 2.1.2'
end

target 'iOSCommunications' do
  swift_protobuf_pod
  zip_pod
end

target 'PolarBleSdk' do
  swift_protobuf_pod
  zip_pod
end

target 'PolarBleSdkWatchOs' do
  platform :watchos, '5.0'
  swift_protobuf_pod
end

target 'iOSCommunicationsTests' do
end

target 'PolarBleSdkTests' do
end
